name: Build on Windows

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - magistra

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '> 1.15.0'
      - name: Run tests
        run: make test
      - name: Build
        run: make mrtg_exporter
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: mrtg_exporter
          path: mrtg_exporter
